# Generated by Django 4.0.1 on 2022-02-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benshop', '0002_basket_product_order_basketitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(default='phone', max_length=200),
            preserve_default=False,
        ),
    ]
